title: Anubhav Garg # your name (or website title) here
logo: "/images/0.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Research Engineer at Cisco. 
  <br><br>
  Leading the research efforts in AutoML, particularly Neural Architecture Search (NAS). Has published a prior project on budgeted NAS at NeurIPSMetalearnWorkshop 2019 and another project, Katib-NAS at OpML2019.
  <br><br>
  <a href="https://www.linkedin.com/in/anubhavgarg5/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
